# Generated by Django 6.0.5 on 2026-06-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='images/users_profile_pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pronounse',
            field=models.CharField(choices=[('he/him', 'HE/HIM'), ('she/her', 'SHE/HER')], default='no_disclosable'),
        ),
        migrations.AddField(
            model_name='profile',
            name='single_status',
            field=models.BooleanField(default=False),
        ),
    ]
