# Generated by Django 6.0.5 on 2026-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_age_profile_profile_pic_profile_pronounse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pronounse',
            field=models.CharField(choices=[('he/him', 'HE/HIM'), ('she/her', 'SHE/HER')]),
        ),
    ]
