# Generated by Django 6.0.5 on 2026-06-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_pronounse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/users_profile_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronounse',
            field=models.CharField(blank=True, choices=[('he/him', 'HE/HIM'), ('she/her', 'SHE/HER')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='single_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
