# Generated by Django 6.0.5 on 2026-05-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photes/product_images'),
        ),
    ]
