# Generated by Django 6.0.5 on 2026-06-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_products',
            name='product_old_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
